Repository bgo-bioimagerie/platformmanager, pull requests merged in 2022-09, with the labels that each got.

#707 [invoice] speedup pdf generation with details (sql refactoring)
  CHANGELOG.md
  Modules/booking/Model/BookingInvoice.php
  Modules/invoices/View/Invoiceglobal/editAction.php
  Modules/services/Model/ServicesInvoice.php
Labels: enhancement

#705 Make client institutionform faculative
  CHANGELOG.md
  Modules/clients/ClientsRouting.php
  Modules/clients/Controller/ClientslistController.php
  Modules/clients/Form/AddressForm.php
  Modules/clients/View/Clientslist/editAction.php
  Modules/clients/View/Clientslist/editAction.twig
  Modules/clients/View/Clientslist/editdeliveryaddressAction.php
  Modules/clients/View/Clientslist/editinvoiceaddressAction.php
  Modules/clients/View/Clientslist/indexAction.php
  Modules/clients/View/Clientslist/indexAction.twig
  Modules/clients/View/layout.twig
Labels: enhancement

#616 Feature satisfaction campaigns
  Config/conf.ini.sample
  Config/conf.yaml.sample
  Config/conf_test.ini
  Config/conf_test.yaml
  Framework/Configuration.php
  Framework/Events.php
  Framework/Request.php
  Framework/Router.php
  Modules/booking/Model/BkCalendarEntry.php
  Modules/catalog/Controller/CatalogpublicController.php
  Modules/core/Model/CoreInstall.php
  Modules/core/Model/CoreSpace.php
  Modules/rating/Controller/RatingController.php
  Modules/rating/Controller/RatingconfigController.php
  Modules/rating/Model/Rating.php
  Modules/rating/Model/RatingInstall.php
  Modules/rating/Model/RatingTranslator.php
  Modules/rating/RatingRouting.php
  Modules/rating/View/Rating/campaignAction.php
  Modules/rating/View/Rating/campaignsAction.php
  Modules/rating/View/Rating/indexAction.php
  Modules/rating/View/Rating/navbar.twig
  Modules/rating/View/Rating/rateAction.php
  Modules/rating/View/Rating/surveyAction.php
  Modules/rating/View/Ratingconfig/indexAction.php
  Modules/services/Model/SeProject.php
  bin/pfm-helpdesk.php
  db/upgrade/1655908007_add_rating_install.php
  doc/content/modules/_index.md
  doc/content/modules/module/rating.md
  docker/setup.sh
  externals/pfm/star-rating/README.md
  externals/pfm/star-rating/VueStarRating.umd.js
  externals/pfm/star-rating/VueStarRating.umd.min.js
  externals/pfm/star-rating/vue2-star-rating/LICENSE
  externals/pfm/star-rating/vue2-star-rating/README.md
  externals/pfm/star-rating/vue2-star-rating/changelog.md
  externals/pfm/star-rating/vue2-star-rating/dist/VueStarRating.common.js
  externals/pfm/star-rating/vue2-star-rating/dist/VueStarRating.common.js.map
  externals/pfm/star-rating/vue2-star-rating/dist/VueStarRating.umd.js
  externals/pfm/star-rating/vue2-star-rating/dist/VueStarRating.umd.js.map
  externals/pfm/star-rating/vue2-star-rating/dist/VueStarRating.umd.min.js
  externals/pfm/star-rating/vue2-star-rating/dist/VueStarRating.umd.min.js.map
  externals/pfm/star-rating/vue2-star-rating/dist/demo.html
  externals/pfm/star-rating/vue2-star-rating/package.json
  externals/pfm/star-rating/vue2-star-rating/src/classes/AlphaColor.js
  externals/pfm/star-rating/vue2-star-rating/src/index.js
  externals/pfm/star-rating/vue2-star-rating/src/star-rating.vue
  externals/pfm/star-rating/vue2-star-rating/src/star.vue
  phpunit.xml
  tests/BaseTest.php
  tests/RatingBaseTest.php
  tests/admin/CoreAdminTest.php
  tests/bootstrap.php
  tests/manager/RatingTest.php
Labels: new feature

#663 Feature custom plans
  CHANGELOG.md
  Config/conf.yaml.sample
  Framework/Configuration.php
  Modules/core/Controller/CoreaboutController.php
Labels: enhancement

#526 manage plan limits with config.yaml limits.resource=4 for example
  Config/conf.yaml.sample
  Framework/Configuration.php
  Modules/core/View/Coreabout/plansAction.twig
  Modules/resources/Controller/ResourcesinfoController.php
Labels: prio/low, new feature

#716 make confirmation email optional at booking, closes #627
  CHANGELOG.md
  Modules/booking/Controller/BookingdefaultController.php
  Modules/booking/Model/BookingTranslator.php
  Modules/booking/View/Bookingdefault/addreservationAction.php
Labels: enhancement
