Repository bgo-bioimagerie/platformmanager, pull requests merged in 2022-02, with the labels that each got.

#554 [core] code cleanup
  CHANGELOG.md
  Framework/TableView.php
  Framework/pm_popup.css
  Framework/ti.php
  Modules/antibodies/View/Antibodieslist/indexAction.php
  Modules/antibodies/View/Antibodieslist/indexAction_1.php
  Modules/antibodies/View/Protocols/editAction.php
  Modules/antibodies/View/navbar.php
  Modules/antibodies/View/navbar.twig
  Modules/booking/Controller/BookinginvoiceController.php
  Modules/booking/Model/BkBookingSettings.php
  Modules/booking/Model/BkCalQuantities.php
  Modules/booking/Model/BkCalSupInfo.php
  Modules/booking/Theme/styleagenda.css
  Modules/booking/View/Booking/agendafunction.php
  Modules/booking/View/Booking/bookday.php
  Modules/booking/View/Booking/bookfunction.php
  Modules/booking/View/Bookingblock/indexAction.php
  Modules/booking/View/Bookingstatisticauthorizations/authorizedusersAction.php
  Modules/booking/View/Bookingstatistics/grrAction.php
  Modules/bulletjournal/Model/BjCollection.php
  Modules/bulletjournal/Model/BjEvent.php
  Modules/bulletjournal/Model/BjTask.php
  Modules/bulletjournal/View/Bjcollections/viewAction.php
  Modules/bulletjournal/View/Bjmigrations/indexHeader.php
  Modules/bulletjournal/View/Bjmigrations/indexTasks.php
  Modules/bulletjournal/View/Bjnotes/indexHeader.php
  Modules/bulletjournal/View/Bjnotes/indexMonth.php
  Modules/catalog/View/Catalogpublic/antibodies.php
  Modules/catalog/View/Catalogpublic/indexAction.php
  Modules/catalog/View/Catalogpublic/toolbar.php
  Modules/catalog/View/Catalogview/antibodies.php
  Modules/catalog/View/Catalogview/resourcesAction.php
  Modules/com/View/Comhome/news.php
  Modules/core/Model/CoreTranslator.php
  Modules/core/View/Coreabout/privacyAction.twig
  Modules/core/View/Corespaceaccess/navbar.twig
  Modules/invoices/View/Invoiceglobal/editAction.php
  Modules/mailer/View/Mailer/indexAction.php
  Modules/resources/View/Resourceshelp/areaHelp.php
  Modules/resources/View/Resourceshelp/categoryHelp.php
  Modules/resources/View/Resourceshelp/eventsHelp.php
  Modules/resources/View/Resourceshelp/responsibleHelp.php
  Modules/resources/View/Resourceshelp/statesHelp.php
  Modules/resources/View/Resourceshelp/visaHelp.php
  Modules/resources/View/navbar.php
  Modules/services/View/navbar.php
Labels: enhancement

#547 [invoices] Feature async
  CHANGELOG.md
  Framework/Events.php
  Modules/booking/Controller/BookinginvoiceController.php
  Modules/booking/Model/BookingInvoice.php
  Modules/booking/Model/BookingTranslator.php
  Modules/booking/Model/BookinginvoiceTranslator.php
  Modules/core/Model/CoreVirtual.php
  Modules/core/View/Corespaceaccess/indexAction.php
  Modules/invoices/Controller/InvoiceglobalController.php
  Modules/invoices/Controller/InvoicesController.php
  Modules/invoices/Controller/InvoiceslistController.php
  Modules/invoices/Model/GlobalInvoice.php
  Modules/invoices/Model/InInvoice.php
  Modules/invoices/Model/InvoicesTranslator.php
  Modules/invoices/View/Invoiceglobal/indexAction.php
  Modules/invoices/View/Invoiceslist/indexAction.php
  Modules/services/Controller/ServicesinvoiceorderController.php
  Modules/services/Controller/ServicesinvoiceprojectController.php
  Modules/services/Model/SeService.php
  Modules/services/Model/ServicesInvoice.php
  Modules/services/View/Servicesinvoiceproject/indexAction.php
  tests/InvoicesBaseTest.php
  tests/manager/InvoicesTest.php
Labels: bug, enhancement

#562 Feature bksched scale
  CHANGELOG.md
  Modules/booking/Controller/BookingdefaultController.php
  Modules/booking/Model/BkScheduling.php
Labels: enhancement

#556 [booking] on calendar, manage user infos options (name, phone,...)
  CHANGELOG.md
  Modules/booking/Controller/BookingconfigController.php
  Modules/booking/Model/BkBookingSettings.php
  Modules/booking/View/Booking/agendafunction.php
  Modules/booking/View/Booking/bookday.php
  Modules/booking/View/Booking/bookdayarea.php
  Modules/booking/View/Booking/bookfunction.php
  Modules/booking/View/Booking/bookmonth.php
  Modules/booking/View/Booking/bookweek.php
  Modules/booking/View/Booking/bookweekarea.php
  Modules/booking/View/Bookingconfig/summaryForm.php
  db/upgrade/1643894167_update_bk_booking_settings_isvisible.php
Labels: enhancement

#560 Feature cal refactor
  CHANGELOG.md
  Modules/booking/Controller/BookingController.php
  Modules/booking/Controller/BookingdefaultController.php
  Modules/booking/View/Booking/agendafunction.php
  Modules/booking/View/Booking/bookday.php
  Modules/booking/View/Booking/bookdayarea.php
  Modules/booking/View/Booking/bookfunction.php
  Modules/booking/View/Booking/bookmonth.php
  Modules/booking/View/Booking/bookweek.php
  Modules/booking/View/Booking/bookweekarea.php
  Modules/booking/View/Booking/caldisplay.php
  Modules/booking/View/Bookingdefault/addreservationAction.php
Labels: enhancement

#569 add interdependant resources use case to doc
  CHANGELOG.md
  doc/content/modules/module/booking.md
  doc/content/use_cases/interdependant_resources.md
  doc/static/packages_1.png
  doc/static/packages_2.png
  doc/static/packages_3.png
  doc/static/packages_4.png
Labels: doc

#576 add missing image i doc for packages UC
  doc/content/use_cases/interdependant_resources.md
Labels: doc

#535 Record and show mailer messages
  CHANGELOG.md
  Modules/core/Model/CoreSpaceUser.php
  Modules/core/Model/CoreTranslator.php
  Modules/mailer/Controller/MailerController.php
  Modules/mailer/Controller/MailerconfigController.php
  Modules/mailer/MailerRouting.php
  Modules/mailer/Model/Mailer.php
  Modules/mailer/Model/MailerTranslator.php
  Modules/mailer/View/Mailer/indexAction.php
  db/upgrade/1642743110_add_mailer_table.php
Labels: fixed_in_dev, new feature

#572 Feature simple space template
  CHANGELOG.md
  Framework/Controller.php
  Modules/booking/Controller/BookingaccessibilitiesController.php
  Modules/booking/Controller/BookingschedulingController.php
  Modules/booking/Model/BkAccess.php
  Modules/booking/Model/BkAuthorization.php
  Modules/booking/Model/BkCalendarEntry.php
  Modules/booking/Model/BkScheduling.php
  Modules/booking/Model/BookingTranslator.php
  Modules/clients/Controller/ClientscompanyController.php
  Modules/clients/Controller/ClientslistController.php
  Modules/clients/Controller/ClientsuseraccountsController.php
  Modules/clients/Model/ClClientUser.php
  Modules/clients/Model/ClientsTranslator.php
  Modules/core/Controller/CorespaceadminController.php
  Modules/core/Model/CorePendingAccount.php
  Modules/core/Model/CoreTranslator.php
  Modules/core/View/Corespaceadmin/editAction.twig
  Modules/core/View/Corespaceuser/editAction.twig
  Modules/resources/Controller/ResourcesinfoController.php
  Modules/resources/Controller/RevisasController.php
  Modules/resources/Model/ResourcesTranslator.php
  Modules/users/Model/UsersTranslator.php
Labels: enhancement
